// Generated by HWClassLibrary.sqlass.T4.Context
// Timestamp: 2012-04-16T01:57:07.3445012+02:00
#region Generated Code

using System;
using System.Collections.Generic;
using System.Linq;
using HWClassLibrary.Debug;
using HWClassLibrary.Helper;
using HWClassLibrary.sqlass;
using HWClassLibrary.sqlass.MetaData;

namespace sqlass.Tables
{
    public partial class Customer 
        : ISQLSupportProvider        
        , ISQLKeyProvider<int>    
    { 
        public int Id; 
        public string Name; 
        public Address Address; 
        public Address DeliveryAddress;

        ISQLSupport ISQLSupportProvider.SQLSupport{get{return new SQLSupport.Customer(this);}} 
        int ISQLKeyProvider<int>.SQLKey { get { return Id; } }    
    }
}

namespace sqlass.SQLSupport
{
    public partial class Customer: ISQLSupport
    {
        readonly Tables.Customer _target;
        public Customer(Tables.Customer target){_target = target;}

        string ISQLSupport.Insert
        {
            get
            {
                var result = "insert into Customer values("; 
                result += _target.Id.SQLFormat();
                result += ", "; 
                result += _target.Name.SQLFormat();
                result += ", "; 
                result += _target.Address.SQLFormat();
                result += ", "; 
                result += _target.DeliveryAddress.SQLFormat();
                result += ")";   

                return result;
            }
        }

        public static readonly Table MetaDataSupport = new Table
        (
            TableName.Find("", "", "Customer"),
            () => new []
            { 

                new Column
                {
                    Name = "Id",
                    Type = typeof(int),
                    IsKey = true,
                    IsNullable = false,
                }, 

                new Column
                {
                    Name = "Name",
                    Type = typeof(string),
                    IsKey = false,
                    IsNullable = false,
                }, 

                new Column
                {
                    Name = "Address",
                    Type = typeof(int),
                    IsKey = false,
                    IsNullable = false,                    
                    ReferencedTable = Address.MetaDataSupport
                }, 

                new Column
                {
                    Name = "DeliveryAddress",
                    Type = typeof(int),
                    IsKey = false,
                    IsNullable = true,                    
                    ReferencedTable = Address.MetaDataSupport
                },   
            
            },
            (record, context) => new Tables.Customer
            { 
                Id = (record["Id"].Convert< int >()), 
                Name = (record["Name"].Convert< string >()), 
                Address = ((Context)context).Container.Address[record["Address"].Convert< int >()], 
                DeliveryAddress = ((Context)context).Container.Address[record["DeliveryAddress"].Convert< int? >()],   
            }
        );
    }
}

#endregion Generated Code
