// Generated by HWClassLibrary.sqlass.T4.Context
// Timestamp: 2011-11-02T04:32:27.3047722+01:00
#region Generated Code

using System;
using System.Collections.Generic;
using System.Linq;
using HWClassLibrary.Debug;
using HWClassLibrary.sqlass;

namespace sqlass.Tables
{
    using sqlass;

    sealed public partial class Customer 
        : ISQLSupportProvider        
        , ISQLKeyProvider<int>    
    { 
        public int Id; 
        public string Name; 
        public Address Address; 
        public Address DeliveryAddress;

        ISQLSupport ISQLSupportProvider.SQLSupport{get{return new SQLSupport.Customer(this);}} 
        int ISQLKeyProvider<int>.SQLKey { get { return Id; } }    
    }
}

namespace sqlass.SQLSupport
{
    using sqlass;

    public partial class Customer: ISQLSupport
    {
        readonly Tables.Customer _target;
        public Customer(Tables.Customer target){_target = target;}

        string ISQLSupport.Insert
        {
            get
            {
                var result = "insert into Customer values("; 
                result += _target.Id.SQLFormat();
                result += ", "; 
                result += _target.Name.SQLFormat();
                result += ", "; 
                result += _target.Address.SQLFormat();
                result += ", "; 
                result += _target.DeliveryAddress.SQLFormat();
                result += ")";   

                return result;
            }
        }

        public static MetaDataSupport MetaDataSupport = new MetaDataSupport
        {
            TableName = "Customer",
            CreateTable = "create table Customer\n"
            + "(\n" 
            + "\tId int primary key not null,\n" 
            + "\tName varchar not null,\n" 
            + "\tAddress int not null,\n" 
            + "\tDeliveryAddress int null\n"   
            + ")\n"
            ,
        };
    }
}

#endregion Generated Code
