// Generated by HWClassLibrary.sqlass.T4.Context
// Timestamp: 2011-10-30T22:45:55.3695933+01:00
#region Generated Code

using HWClassLibrary.sqlass;
using sqlass.Tables;

namespace sqlass
{
    sealed public class Container
    { 
        public Table<Customer> Customer; 
        public Table<Address> Address;                        
        
        public Container(Context context)
        { 
            Customer = new Table<Customer>(context, "Customer"); 
            Address = new Table<Address>(context, "Address");
        }
    }

    sealed public partial class Context: HWClassLibrary.sqlass.Context
    {
        public readonly Container Container;

        public Context()
        {
            Container = new Container(this);
        }
    }
}

#endregion Generated Code
