// Generated by HWClassLibrary.sqlass.T4.Context
// Timestamp: 2011-12-06T07:51:51.1645911+01:00
#region Generated Code

using System;
using HWClassLibrary.Helper;
using HWClassLibrary.sqlass;
using sqlass.Tables;

namespace sqlass
{
    sealed public class Container
    { 
        public readonly Table<Customer, int> Customer; 
        public readonly Table<Address, int> Address;
        public Container(Context context)
        { 
            Customer = new Table<Customer, int>(context, SQLSupport.Customer.MetaDataSupport); 
            Address = new Table<Address, int>(context, SQLSupport.Address.MetaDataSupport);
        }
    }

    sealed public partial class Context: HWClassLibrary.sqlass.Context
    {
        public readonly Container Container;
        public Context(){Container = new Container(this);}
        public void UpdateDatabase() { UpdateDatabase(Container); }
    }
}

#endregion Generated Code
