// Generated by HWClassLibrary.sqlass.T4.Context
// Timestamp: 2011-11-01T17:39:17.8283269+01:00
#region Generated Code

using System;
using HWClassLibrary.Helper;
using HWClassLibrary.sqlass;
using sqlass.Tables;

namespace sqlass
{
    sealed public class Container
    { 
        public Table<Customer> Customer; 
        public Table<Address> Address;                        
        
        public Container(Context context)
        { 
            Customer = new Table<Customer>(context, "main.Customer"); 
            Address = new Table<Address>(context, "Address");
        }
    }

    sealed public partial class Context: HWClassLibrary.sqlass.Context
    {
        readonly DictionaryEx<Type, MetaDataSupport> _metaData;
        public readonly Container Container;

        public Context()
        {
            Container = new Container(this);
            _metaData = new DictionaryEx<Type, MetaDataSupport>
                        { 
                            {typeof(Tables.Customer), SQLSupport.Customer.MetaDataSupport}, 
                            {typeof(Tables.Address), SQLSupport.Customer.MetaDataSupport},                        };
        }

        public void UpdateDatabase() { UpdateDatabase(Container, _metaData); }
    }
}

#endregion Generated Code
